### ISSUE TITLE
Address error within eval_plots.py when running on outputs that don't have data covering all benchmark types

### ISSUE THREAD

**Issue by RyanSpies-NOAA** [NOAA-OWP/inundation-mapping#1303] opened 2024-09-24 15:55 UTC
Steps to reproduce:
1) create or use a set of FIM outputs that only cover some of the benchmark data sources (e.g. one BLE HUC)
2) run `synthesize_test_cases.py`
3) run `eval_plots.py` or `eval_plots_stackedbar.py`

Error message below:

Traceback (most recent call last):
  File "//foss_fim/tools/eval_plots.py", line 1037, in <module>
    eval_plots(metrics_csv=m, workspace=w, versions=v, stats=s, spatial=sp, fim_1_ms=f, site_barplots=i)
  File "//foss_fim/tools/eval_plots.py", line 729, in eval_plots
    barplot(
  File "//foss_fim/tools/eval_plots.py", line 328, in barplot
    axes = sns.barplot(
  File "/usr/local/lib/python3.10/dist-packages/seaborn/categorical.py", line 2755, in barplot
    plotter = _BarPlotter(x, y, hue, data, order, hue_order,
  File "/usr/local/lib/python3.10/dist-packages/seaborn/categorical.py", line 1532, in __init__
    self.establish_colors(color, palette, saturation)
  File "/usr/local/lib/python3.10/dist-packages/seaborn/categorical.py", line 707, in establish_colors
    lum = min(light_vals) * .6
ValueError: min() arg is an empty sequence

**Comment by RobHanna-NOAA** [comment] 2024-12-11 20:14
This is a duplicate of 1362, but we will close that one and put those notes into this card, keeping this card open:

------------------

Eval plots is erroring out with a ValueError of "min() arg is an empty sequence.

	The following AHPS sites are considered "BAD_SITES":  baki3, cart2, eagi1, efdn7, erwn6, grfi2, kcdm7, ksdm7, levk1, lkcm7, loun7, lrlm7, mcri2, mtao1, roun6, rwdn4, vcni3
	The following query is used to filter AHPS:  not flow.isnull() & masked_perc<97 & not nws_lid in @BAD_SITES
	Traceback (most recent call last):
	  File "//foss_fim/tools/eval_plots.py", line 1036, in <module>
	    eval_plots(metrics_csv=m, workspace=w, versions=v, stats=s, spatial=sp, fim_1_ms=f, site_barplots=i)
	  File "//foss_fim/tools/eval_plots.py", line 728, in eval_plots
	    barplot(
	  File "//foss_fim/tools/eval_plots.py", line 327, in barplot
	    axes = sns.barplot(
	  File "/usr/local/lib/python3.10/dist-packages/seaborn/categorical.py", line 2755, in barplot
	    plotter = _BarPlotter(x, y, hue, data, order, hue_order,
	  File "/usr/local/lib/python3.10/dist-packages/seaborn/categorical.py", line 1532, in __init__
	    self.establish_colors(color, palette, saturation)
	  File "/usr/local/lib/python3.10/dist-packages/seaborn/categorical.py", line 707, in establish_colors
	    lum = min(light_vals) * .6
	ValueError: min() arg is an empty sequence
root@421deec6b5a0:/# ^C

It has been seen against against a couple of different pipeline tests including a huc set of "07080103 07080208 12040101 12040103 12090301". Between the combination of those HUCs, they cover all five of the different test_case types.

- 07080103 (ras2fim, ifc)
- 07080208 (ras2fim, usgs)
- 12040101 (nws, ble)
- 12040103 (ble, nws, usgs)
- 12090301 (ble, ifc, nws, and usgs)

----------------
Matt:

I ran fim_pipeline, synth, and eval_plots on the same set of HUCs ("07080103 07080208 12040101 12040103 12090301") on my EC2 using the dev image but didn't get the error. I'll try on prod3.

**Comment by mluck** [comment] 2024-12-12 21:01
Unable to replicate this particular error. It may have been resolved with an update to seaborn. We'll keep an eye out for it and reopen this issue if it happens again.

**Closed by mluck** 2024-12-12 21:01 UTC
Labels: bug
