### ISSUE TITLE
[5pt] test_case_by_hydro_id.py bug - negative geometries

### ISSUE THREAD

**Issue by RobHanna-NOAA** [NOAA-OWP/inundation-mapping#1203] opened 2024-06-27 18:43 UTC
During an attempt to run fim_4_5_2_0 for test_case_by_hydro_id.py it errored out: 
```
listing_test_cases_with_updates
/data/previous_fim/fim_4_5_2_0/04300109 does not exist
projecting to 3857/fim_4_5_2_0/10280103
Traceback (most recent call last):
  File "//foss_fim/tools/test_case_by_hydro_id.py", line 302, in <module>
    csv_output = csv_output.to_crs('EPSG:3857')
  File "/usr/local/lib/python3.10/dist-packages/geopandas/geodataframe.py", line 1407, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)
  File "/usr/local/lib/python3.10/dist-packages/geopandas/geoseries.py", line 1170, in to_crs
    self.values.to_crs(crs=crs, epsg=epsg), index=self.index, name=self.name
  File "/usr/local/lib/python3.10/dist-packages/geopandas/array.py", line 855, in to_crs
    raise ValueError(
ValueError: Cannot transform naive geometries.  Please set a crs on the object first.
```
**- An Alaska thing maybe?**

Command used in UCS3:

`python foss_fim/tools/test_case_by_hydro_id.py -v fim_4_5_2_0 -g /data/fim_performance/fim_4_5_2_0/fim_performance_catchments.gpkg -b all`

Note: I believe this can be run on EC2, but if not, you might have to go to DEV1.
The two prerequite files are at /data/fim_performance/fim_4_5_2_0/ are already generated for fim_4_5_2_0 and are there.

Update: it has to be run on EC2 as it needs the fim run's synthesize test case output data.

**Comment by CarsonPruitt-NOAA** [comment] 2024-06-27 19:27
I think I may have fixed this. Can you try running on my FB: `dev-fim-performance-bug`

**Comment by mluck** [comment] 2024-08-21 13:46
This is a duplicate of #1240.

**Closed by mluck** 2024-08-21 13:46 UTC
Labels: bug, High Priority, FIM4
